add OWNCLOUD_INTEGRITY_CHECK_DISABLED var for testing
owncloud-docker/base pull request #137
Opened 2020-10-28 21:44 UTC by micbar

2020-10-28 21:57 UTC, jnweiger requested changes
please double check the inverted logic...

(Okay to drop some 10.3.0 rebuilds en-passant!)

2020-10-28 21:57 UTC, jnweiger commented on v20.04/overlay/etc/templates/config.php
> +    $config['integrity.check.disabled'] = getenv('OWNCLOUD_INTEGRITY_CHECK_DISABLED') == 'false';
```suggestion
    $config['integrity.check.disabled'] = getenv('OWNCLOUD_INTEGRITY_CHECK_DISABLED') == 'true';
```

The negation of a disable flag ... is ... naaah....

2020-10-28 23:05 UTC, micbar commented on v20.04/overlay/etc/templates/config.php
> +    $config['integrity.check.disabled'] = getenv('OWNCLOUD_INTEGRITY_CHECK_DISABLED') == 'false';
no no, the default should be `false`

2020-10-28 23:07 UTC, micbar commented on v20.04/overlay/etc/templates/config.php
> +    $config['integrity.check.disabled'] = getenv('OWNCLOUD_INTEGRITY_CHECK_DISABLED') == 'false';
In english: the default case should have the integrity check enabled

2020-10-29 08:27 UTC, jnweiger approved these changes

2020-10-29 08:28 UTC, merged