add OWNCLOUD_SESSION_FORCED_LOGOUT_TIMEOUT
owncloud-docker/base pull request #205
Opened 2022-06-01 00:38 UTC by voroyam

add `OWNCLOUD_SESSION_FORCED_LOGOUT_TIMEOUT` variable.

It expires the session and logs the user out after set time.

2022-06-01 07:31 UTC, xoxys requested changes
See comments.

2022-06-01 07:31 UTC, xoxys commented on v20.04/overlay/etc/templates/config.php
> +
Fix whitespacing.

2022-06-01 07:50 UTC, voroyam commented
> * `latest` image missing

I don't understand what you mean

2022-06-01 07:50 UTC, xoxys requested changes

2022-06-01 07:50 UTC, xoxys commented on README.md
> +  Expires the session and logs the user out after set time. (see [documentation](https://doc.owncloud.com/server/next/admin_manual/configuration/server/config_sample_php_parameters.html#enable-to-for
Please use `/latest/` links not `/next/`

2022-06-01 07:52 UTC, xoxys commented
> I don't understand what you mean

There are two images, one based on php-ubuntu20.04 and one based on php-latest. 

The latest one (https://github.com/owncloud-docker/base/tree/master/latest) is not covered in your PR.

2022-06-01 08:58 UTC, voroyam commented on README.md
> +  Expires the session and logs the user out after set time. (see [documentation](https://doc.owncloud.com/server/next/admin_manual/configuration/server/config_sample_php_parameters.html#enable-to-for
there is only `next` in the switcher menu

![image](https://user-images.githubusercontent.com/24212810/171367319-e133dc25-d7c2-4f24-9306-9bd6cfb14da2.png)

can you explain why you prefer latest?

2022-06-01 09:05 UTC, xoxys commented on README.md
> +  Expires the session and logs the user out after set time. (see [documentation](https://doc.owncloud.com/server/next/admin_manual/configuration/server/config_sample_php_parameters.html#enable-to-for
Because latest redirects always to the latest stable release while next container nor released features.

2022-06-01 09:07 UTC, xoxys commented
> * declare statement missing (see https://github.com/owncloud-docker/base/blob/master/v20.04/overlay/etc/entrypoint.d/85-others.sh#L27-L28)

This one is still missing.

2022-06-02 08:15 UTC, xoxys approved these changes

2022-06-02 08:25 UTC, merged