refactor: normalize shell formatting and add linting to ci
owncloud-docker/base pull request #225
Opened 2022-09-13 08:43 UTC by xoxys

2022-09-13 13:16 UTC, phil-davis approved these changes
Looks OK

2022-09-13 13:16 UTC, phil-davis commented on v20.04/overlay/etc/templates/config.php
> -  if (getenv('OWNCLOUD_INTEGRITY_CHECK_DISABLED') != '') {
Note: `OWNCLOUD_INTEGRITY_CHECK_DISABLED` is removed.

2022-09-13 13:24 UTC, xoxys commented on .drone.star
> +                "grep -ErlI '^#!(.*/|.*env +)(sh|bash|ksh)' %s/overlay/ | xargs shellcheck" % (config["path"]),
I would love it shellcheck would have a recursive parameter included :D sadly they don't, so some magic is needed to utilize a regex grep to parse the shebang of a file to ensure it's a `sh|bash|ksh` script. Otherwise, shellcheck will fail.

2022-09-13 13:24 UTC, xoxys commented on latest/overlay/etc/owncloud.d/40-apps.sh
> +        rm -r "${OWNCLOUD_VOLUME_APPS:?}/${VAL}"
Yes, that's intended to prevent `rm -rf /` in any case, see https://www.shellcheck.net/wiki/SC2115

2022-09-13 13:25 UTC, xoxys commented on v20.04/overlay/etc/templates/config.php
> -  if (getenv('OWNCLOUD_INTEGRITY_CHECK_DISABLED') != '') {
Yes because only partially implemented in v20.04. `latest` is missing completely, no documentation, no defaults handling. Will re-implement it in a standalone PR.

2022-09-13 13:26 UTC, xoxys commented
@phil-davis Thanks for taking the time!

2022-09-13 13:29 UTC, TheRealBro requested changes
see comments

2022-09-13 13:29 UTC, TheRealBro commented on latest/overlay/etc/owncloud.d/40-apps.sh
> +        rm -r "${OWNCLOUD_VOLUME_APPS:?}/${VAL}"
what is the ``` ? ``` doing here?

2022-09-13 13:29 UTC, TheRealBro commented on latest/overlay/usr/bin/cronjob
> +  if [[ "$(id -u)" == "0" ]]; then
same as above

2022-09-13 13:29 UTC, TheRealBro commented on latest/overlay/usr/bin/occ
> +if [[ "$(id -u)" == "0" ]]; then
same here

2022-09-13 13:29 UTC, TheRealBro commented on v20.04/overlay/etc/entrypoint.d/98-overwrite.sh
> +if [[ "$(id -gn)" == "root" ]]; then
same as above - consistence

2022-09-13 13:29 UTC, TheRealBro commented on latest/overlay/etc/entrypoint.d/98-overwrite.sh
> +if [[ "$(id -gn)" == "root" ]]; then
see below... comment about consistent check

2022-09-13 13:29 UTC, TheRealBro commented on v20.04/overlay/etc/owncloud.d/40-apps.sh
> +        rm -r "${OWNCLOUD_VOLUME_APPS:?}/${VAL}"
what is the ```?``` doing here?

2022-09-13 13:31 UTC, TheRealBro commented on latest/overlay/etc/owncloud.d/40-apps.sh
> +        rm -r "${OWNCLOUD_VOLUME_APPS:?}/${VAL}"
closed see above

2022-09-13 13:31 UTC, TheRealBro commented on v20.04/overlay/etc/owncloud.d/40-apps.sh
> +        rm -r "${OWNCLOUD_VOLUME_APPS:?}/${VAL}"
closed see above

2022-09-13 13:37 UTC, xoxys commented on latest/overlay/etc/owncloud.d/35-logging.sh
> +  if [[ "$(id -u)" == "0" ]]; then
Agree, changed to number in all cases.

2022-09-13 13:40 UTC, TheRealBro reviewed
:+1:

2022-09-14 07:09 UTC, TheRealBro approved these changes
make love, not war.
LGTM

2022-09-14 07:10 UTC, merged