added OBJECTSTORE_PART_SIZE and OBJECTSTORE_CONCURENCY
owncloud-docker/base pull request #260
Opened 2023-02-27 11:52 UTC by voroyam

2023-02-27 13:29 UTC, xoxys requested changes
Just a small one to use the same URLs that are already used for the objectstore vars.

2023-02-27 13:29 UTC, xoxys commented on ENVIRONMENT.md
> +  part size, in bytes, to use when doing a multipart upload (see [documentation](https://doc.owncloud.com/server/latest/admin_manual/configuration/files/external_storage/s3_compatible_object_storage_
```suggestion
  part size, in bytes, to use when doing a multipart upload (see [documentation](https://doc.owncloud.com/server/latest/admin_manual/configuration/files/external_storage/s3_compatible_object_storage_as_primary.html)).
```

2023-02-27 13:29 UTC, xoxys commented on ENVIRONMENT.md
> +  maximum number of concurrent UploadPart operations allowed during the multipart upload (see [documentation](https://doc.owncloud.com/server/latest/admin_manual/configuration/files/external_storage/
```suggestion
  maximum number of concurrent UploadPart operations allowed during the multipart upload (see [documentation](https://doc.owncloud.com/server/latest/admin_manual/configuration/files/external_storage/s3_compatible_object_storage_as_primary.html)).  
```

2023-02-27 14:14 UTC, d7oc approved these changes
The default `part_size` is unknown to me. Should be checked with engineering. Maybe
@jvillafanez knowns.

Rest LGTM, aside my comments.

2023-02-27 14:14 UTC, d7oc commented on ENVIRONMENT.md
> +- `OWNCLOUD_OBJECTSTORE_CONCURRENCY=5` \
```suggestion
- `OWNCLOUD_OBJECTSTORE_CONCURRENCY=3` \
```

Default concurrency is 3 we should leave the default.

2023-02-27 14:14 UTC, d7oc commented on latest/overlay/etc/entrypoint.d/40-objectstorage.sh
> +[[ -z "${OWNCLOUD_OBJECTSTORE_CONCURRENCY}" ]] && OWNCLOUD_OBJECTSTORE_CONCURRENCY="5"
```suggestion
[[ -z "${OWNCLOUD_OBJECTSTORE_CONCURRENCY}" ]] && OWNCLOUD_OBJECTSTORE_CONCURRENCY="3"
```

see above.

2023-02-27 14:14 UTC, d7oc commented on v20.04/overlay/etc/entrypoint.d/40-objectstorage.sh
> +[[ -z "${OWNCLOUD_OBJECTSTORE_CONCURRENCY}" ]] && OWNCLOUD_OBJECTSTORE_CONCURRENCY="5"
```suggestion
[[ -z "${OWNCLOUD_OBJECTSTORE_CONCURRENCY}" ]] && OWNCLOUD_OBJECTSTORE_CONCURRENCY="3"
```

see above.

2023-02-28 07:50 UTC, jvillafanez commented
> The default part_size is unknown to me. Should be checked with engineering. Maybe
@jvillafanez knowns.

Maybe we should clarify it applies to uploads between ownCloud and S3, not between the client and ownCloud.
I don't think the "multipart" is relevant, and it could also confuse the user because it could be interpreted as if the multipart upload happens between the client and ownCloud. Since the upload happens between ownCloud and S3, whether the upload is multipart or not doesn't seem important to the user; he just need to know that the file will be split in chunks of that size and the chunks will be uploaded to S3.

2023-02-28 08:39 UTC, xoxys commented
That's just a copy/paste + back ref to doc.owncloud.com. If that requires adjustments, it should be adjusted there first. The remaining question is still what's the default part size used by the library?

2023-02-28 09:01 UTC, jvillafanez commented
5 MB according to https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html
>  part_size
    (int, default: int(5242880)) Part size, in bytes, to use when doing a multipart upload. This must between 5 MB and 5 GB, inclusive

2023-02-28 09:11 UTC, voroyam commented
@xoxys leave the `#configuration` at the end of the link or remove it?

2023-02-28 09:12 UTC, xoxys commented
Remove it please.

2023-02-28 09:18 UTC, voroyam commented
doc issue to change the concurrency parameter there to 3 instead of 5
https://github.com/owncloud/docs/issues/4816

2023-02-28 09:21 UTC, voroyam commented
doc issue to change the description of concurrency:
https://github.com/owncloud/docs/issues/4817

2023-02-28 10:21 UTC, xoxys approved these changes

2023-02-28 10:22 UTC, xoxys requested changes

2023-02-28 10:22 UTC, xoxys commented on ENVIRONMENT.md
> +  maximum number of concurrent UploadPart operations allowed during the multipart upload (see [documentation](https://doc.owncloud.com/server/latest/admin_manual/configuration/files/external_storage/
Please start with an uppercase.

2023-02-28 10:22 UTC, xoxys commented on ENVIRONMENT.md
> +  part size, in bytes, applies to uploads between ownCloud and S3 (see [documentation](https://doc.owncloud.com/server/latest/admin_manual/configuration/files/external_storage/s3_compatible_object_st
Please start with an uppercase.

2023-02-28 11:29 UTC, merged