add default_socket_timeout
owncloud-docker/base pull request #265
Opened 2023-03-01 03:56 UTC by voroyam

2023-03-01 07:57 UTC, xoxys requested changes
Please also add it with the default value to https://github.com/owncloud-docker/base/blob/master/v20.04/overlay/etc/php/7.4/mods-available/owncloud.ini (and the latest directory)

2023-03-01 07:57 UTC, xoxys commented on latest/overlay/etc/templates/owncloud.ini.tmpl
> +default_socket_timeout = "${{ .Env.OWNCLOUD_DEFAULT_SOCKET_TIMEOUT }}"
```suggestion
default_socket_timeout = {{ .Env.OWNCLOUD_DEFAULT_SOCKET_TIMEOUT }}
```

2023-03-01 07:57 UTC, xoxys commented on v20.04/overlay/etc/templates/owncloud.ini.tmpl
> +default_socket_timeout = "${{ .Env.OWNCLOUD_DEFAULT_SOCKET_TIMEOUT }}"
```suggestion
default_socket_timeout = {{ .Env.OWNCLOUD_DEFAULT_SOCKET_TIMEOUT }}
```

2023-03-01 10:02 UTC, xoxys approved these changes

2023-03-01 12:06 UTC, phil-davis commented
Note: https://github.com/owncloud-docker/base/commit/9df7aa89b8811702dc99d555d1e0cf07da7d8186
`default_socket_timeoute` had been set to 3600, and was deleted in that commit.
PR #225 
Maybe that was an accidental deletion in that PR?

2023-03-01 12:25 UTC, xoxys commented
I had removed it back in the days because it was not set consistently on all images. Setting it to `60` seconds is the php default and should be fine. What do you think?

2023-03-01 13:42 UTC, voroyam commented
merge?

2023-03-01 14:21 UTC, merged

2023-03-01 14:22 UTC, xoxys commented
@phil-davis Feel free to still add any objections.

2023-03-13 06:14 UTC, phil-davis commented
Looks OK to me.