Update owncloud.cron.tmpl
owncloud-docker/base pull request #273
Opened 2023-03-20 10:32 UTC by voroyam

add dav:cleanup-chunks for chunks cleanup

according to our docs we recommend this.

https://doc.owncloud.com/server/10.12/admin_manual/installation/quick_guides/ubuntu_20_04.html#configure-the-cron-jobs

also on a general basis useful to have, to cleanup the storage.

2023-03-22 09:02 UTC, TheRealBro reviewed
works for me, as it is recommended in the docu, but would wait for a second opinion by @xoxys before merge

2023-03-27 07:39 UTC, xoxys requested changes
Wrong place, needs to be added to https://github.com/owncloud-docker/base/blob/master/v20.04/overlay/usr/bin/cronjob#L12, and it also needs to be added to both versions (latest, v20.04).

2023-03-27 11:09 UTC, xoxys requested changes

2023-03-27 11:09 UTC, xoxys commented on v20.04/overlay/etc/templates/owncloud.cron.tmpl
> +{{ .Env.OWNCLOUD_CROND_SCHEDULE }} www-data /usr/bin/cronjob
Please reset the file and add back the newline char at the end of the file.

2023-03-27 11:26 UTC, xoxys approved these changes

2023-03-27 11:26 UTC, merged