added objectstore variable available storage
owncloud-docker/base pull request #274
Opened 2023-03-22 02:37 UTC by voroyam

new variable was added for the metrics app to fix 
https://github.com/owncloud/enterprise/issues/5384

docs 
https://doc.owncloud.com/server/next/admin_manual/configuration/files/external_storage/s3_compatible_object_storage_as_primary.html#amazon-s3

pr 
https://github.com/owncloud/metrics/pull/159

2023-03-22 08:58 UTC, TheRealBro requested changes
I understand the need for the new variable. But the documentation states 1 TB as example value. Why should we always set this value to 1TB by default in our base image? wouldn't that break other things at some points?

2023-03-22 09:24 UTC, voroyam commented
> wouldn't that break other things at some points?

The value of the variable is just for cosmetics. It shows the total amount of storage, based on that you see a pie chart of used storage vs free storage. As far as I know nothing else depends on that value, for example no quotas. We can leave that value empty. I just need to have that variable in the image so I can use it for the bayernbox image that is based on that

2023-03-22 09:28 UTC, xoxys requested changes
It's just wrong to set a cosmetic value by default for everyone, with a random default. Please set an empty default and make it conditional in the template as we do in e.g. https://github.com/owncloud-docker/base/blob/master/v20.04/overlay/etc/templates/config.php#L4

2023-03-22 09:38 UTC, voroyam commented
> It's just wrong to set a cosmetic value by default for everyone, with a random default. Please set an empty default and make it conditional in the template as we do in e.g. https://github.com/owncloud-docker/base/blob/master/v20.04/overlay/etc/templates/config.php#L4

conditional to what?

2023-03-22 09:39 UTC, TheRealBro commented
> > It's just wrong to set a cosmetic value by default for everyone, with a random default. Please set an empty default and make it conditional in the template as we do in e.g. https://github.com/owncloud-docker/base/blob/master/v20.04/overlay/etc/templates/config.php#L4
> 
> conditional to what?

Conditional, as in the linked example by @xoxys -> if empty -> not set, otherwise set, if it contains a value.

2023-03-22 09:59 UTC, voroyam commented
like this? 

```
if (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE') != '') {
    $availableStorage = array_map('trim', explode(',', getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE')));
  } else {
    $availableStorage = [explode(':', getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'))[0]];
  }
```

2023-03-22 10:07 UTC, TheRealBro commented
> or this?
> 
> ```
> if (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE') != '') {
>     $availableStorage = (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'));
>   }
> ```

Like this ^^ would be the way to go. And in deployment, the value can be set or not set.

2023-03-22 10:12 UTC, voroyam commented
> > or this?
> > ```
> > if (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE') != '') {
> >     $availableStorage = (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'));
> >   }
> > ```
> 
> Like this ^^ would be the way to go. And in deployment, the value can be set or not set.

okay, full thing is this? 

```
<?php

function getObjectstoreFromEnv() {
  if (getenv('OWNCLOUD_OBJECTSTORE_ENABLED') && getenv('OWNCLOUD_OBJECTSTORE_ENABLED') === 'true') {
    return [
      'objectstore' => [
        'class' => getenv('OWNCLOUD_OBJECTSTORE_CLASS'),
        'arguments' => [
          'bucket' => getenv('OWNCLOUD_OBJECTSTORE_BUCKET'),
            if (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE') != '') {
              $availableStorage = (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'));
            }
          'availableStorage' => getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'),
          'part_size' => getenv('OWNCLOUD_OBJECTSTORE_PART_SIZE'),
          'concurrency' => getenv('OWNCLOUD_OBJECTSTORE_CONCURRENCY'),
          'options' => [
            'endpoint' => getenv('OWNCLOUD_OBJECTSTORE_ENDPOINT'),
            'version' => getenv('OWNCLOUD_OBJECTSTORE_VERSION'),
            'region' => getenv('OWNCLOUD_OBJECTSTORE_REGION'),
            'use_path_style_endpoint' => getenv('OWNCLOUD_OBJECTSTORE_PATHSTYLE') === 'true',
            'command.params' => [
              'PathStyle' => getenv('OWNCLOUD_OBJECTSTORE_PATHSTYLE') === 'true',
            ],
            'credentials' => [
              'key'   => getenv('OWNCLOUD_OBJECTSTORE_KEY'),
              'secret'  => getenv('OWNCLOUD_OBJECTSTORE_SECRET'),
            ],
          ],
        ],
      ],
    ];
  }

  return [];
}

$CONFIG = getObjectstoreFromEnv();
```

2023-03-22 10:17 UTC, xoxys requested changes
No, why do you add a dollar now? This was just an example, of course it needs to be adjusted to _this_ particular_  config file and syntax...

2023-03-22 10:17 UTC, xoxys commented on v20.04/overlay/etc/templates/objectstore.php.tmpl
> +          'availableStorage' => getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'),
```suggestion
          if (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE') != '') {
          'availableStorage' => getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'),
          }
```

2023-03-22 10:20 UTC, TheRealBro commented on v20.04/overlay/etc/templates/objectstore.php.tmpl
> +          'availableStorage' => getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'),
HALLELUJAH!

2023-03-22 10:21 UTC, xoxys commented
However, this also might not work as this is part of a return statement... Needs to be tested locally first before it could be merged.

2023-03-22 10:23 UTC, voroyam commented on v20.04/overlay/etc/templates/objectstore.php.tmpl
> +          'availableStorage' => getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'),
```          
'bucket' => getenv('OWNCLOUD_OBJECTSTORE_BUCKET'),
          if (getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE') != '') {
          'availableStorage' => getenv('OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE'),
          },
          'part_size' => getenv('OWNCLOUD_OBJECTSTORE_PART_SIZE'),
```

2023-03-22 10:49 UTC, voroyam commented
does not seem to work:

```
"objectstore": {
            "class": "OCA\\Files_Primary_S3\\S3Storage",
            "arguments": {
                "bucket": "owncloud",
                "part_size": "268435456",
                "concurrency": "3",
                "options": {
                    "endpoint": "http:\/\/scality:8000",
                    "version": "2006-03-01",
                    "region": "us-east-1",
                    "use_path_style_endpoint": true,
                    "command.params": {
                        "PathStyle": true
                    },
                    "credentials": {
                        "key": "***REMOVED SENSITIVE VALUE***",
                        "secret": "***REMOVED SENSITIVE VALUE***"
                    }
                }
            }
        },
```

2023-03-23 09:32 UTC, voroyam commented
Any idea what needs to be changed to get it to work?

2023-03-23 18:58 UTC, voroyam commented
> Inline conditionals within an array definition don't work.

if I put your suggestion in the container goes in to a loop and breaks

2023-03-27 09:00 UTC, xoxys commented
Works for me ... What exactly have you tested? 

```
docker exec -it owncloud_server occ config:system:get objectstore
class: OCA\Files_Primary_S3\S3Storage
arguments:
  bucket: owncloud
  part_size: 5242880
  concurrency: 3
  options:
    endpoint: http://minio:9000
    version: 2006-03-01
    region: us-east-1
    use_path_style_endpoint: true
    command.params:
      PathStyle: true
    credentials:
      key: minioadmin
      secret: minioadmin
  availableStorage: 12345678900000
```

2023-03-27 10:35 UTC, xoxys approved these changes

2023-03-27 10:36 UTC, merged